/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotifyConnectRouteImport } from './routes/spotify-connect'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify-callback'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as LeagueLeagueIdRouteImport } from './routes/league/$leagueId'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppSquadRouteImport } from './routes/_app/squad'
import { Route as AppSeasonRouteImport } from './routes/_app/season'
import { Route as AppOfficeRouteImport } from './routes/_app/office'

const SpotifyConnectRoute = SpotifyConnectRouteImport.update({
  id: '/spotify-connect',
  path: '/spotify-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify-callback',
  path: '/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSquadRoute = AppSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSeasonRoute = AppSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOfficeRoute = AppOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/fixtures': typeof FixturesRoute
  '/scouts': typeof ScoutsRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/spotify-connect': typeof SpotifyConnectRoute
  '/office': typeof AppOfficeRoute
  '/season': typeof AppSeasonRoute
  '/squad': typeof AppSquadRoute
  '/transfers': typeof AppTransfersRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesByTo {
  '/fixtures': typeof FixturesRoute
  '/scouts': typeof ScoutsRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/spotify-connect': typeof SpotifyConnectRoute
  '/office': typeof AppOfficeRoute
  '/season': typeof AppSeasonRoute
  '/squad': typeof AppSquadRoute
  '/transfers': typeof AppTransfersRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/fixtures': typeof FixturesRoute
  '/scouts': typeof ScoutsRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/spotify-connect': typeof SpotifyConnectRoute
  '/_app/office': typeof AppOfficeRoute
  '/_app/season': typeof AppSeasonRoute
  '/_app/squad': typeof AppSquadRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fixtures'
    | '/scouts'
    | '/spotify-callback'
    | '/spotify-connect'
    | '/office'
    | '/season'
    | '/squad'
    | '/transfers'
    | '/league/$leagueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fixtures'
    | '/scouts'
    | '/spotify-callback'
    | '/spotify-connect'
    | '/office'
    | '/season'
    | '/squad'
    | '/transfers'
    | '/league/$leagueId'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/fixtures'
    | '/scouts'
    | '/spotify-callback'
    | '/spotify-connect'
    | '/_app/office'
    | '/_app/season'
    | '/_app/squad'
    | '/_app/transfers'
    | '/league/$leagueId'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  FixturesRoute: typeof FixturesRoute
  ScoutsRoute: typeof ScoutsRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  SpotifyConnectRoute: typeof SpotifyConnectRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotify-connect': {
      id: '/spotify-connect'
      path: '/spotify-connect'
      fullPath: '/spotify-connect'
      preLoaderRoute: typeof SpotifyConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify-callback': {
      id: '/spotify-callback'
      path: '/spotify-callback'
      fullPath: '/spotify-callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/squad': {
      id: '/_app/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof AppSquadRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/season': {
      id: '/_app/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof AppSeasonRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/office': {
      id: '/_app/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof AppOfficeRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppOfficeRoute: typeof AppOfficeRoute
  AppSeasonRoute: typeof AppSeasonRoute
  AppSquadRoute: typeof AppSquadRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOfficeRoute: AppOfficeRoute,
  AppSeasonRoute: AppSeasonRoute,
  AppSquadRoute: AppSquadRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  FixturesRoute: FixturesRoute,
  ScoutsRoute: ScoutsRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  SpotifyConnectRoute: SpotifyConnectRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
